spring:
  application:
    name: eureka-service
server:
  port: 8761
eureka:
  client:
    fetch-registry: false #Esta configuración es para eureka
    register-with-eureka: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/